config/routes.rb
Rails.application.routes.draw do

get '/signup', to: 'user#new'
post '/user', to: 'user#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
root 'gossip#index'
get '/home/team', to: 'home#team'
get '/home/contact', to: 'home#contact'
get '/home/:id', to: 'user#welcome'
post '/home/contact', to: 'home#contact'
resources :gossip
resources :user
resources :city, only: [:show]
resources :comment

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  validates :content, presence: true 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	validates :title, presence: true,  length: { in: 3..30 }
	validates :content, presence: true 
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :gossips
	validates :first_name, :last_name, :description, :age, presence: true
	validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	has_one :city
	has_many :comments
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
 protect_from_forgery with: :exception 

 
 def current_user 
 	@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] 
 end 
 helper_method :current_user 

 def authorize
    redirect_to '/login' unless current_user
  end

def user_is_logged_in
    if !session[:current_user]
        redirect_to login_path
    end
end
  
end

app/controllers/city_controller.rb
class CityController < ApplicationController

	def new
		@city = City.new
	end

	def show
		@city = City.find(params[:id])
		@gossip = Gossip.all
		@user = User.all
	end
	
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def show
		@comment = Comment.all
	end

	def new 
		@comment = Comment.new
	end 

	def create 
		@gossip = Gossip.find(params['gossip_id'])
		@comment = Comment.create!(content: params[:content], gossip: @gossip,user_id: session[:user_id])
    	if @comment.save
      	redirect_to gossip_path(@gossip.id)
    	else
      	redirect_to gossip_path(@gossip.id)
    	end
	end 

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
    	if @comment.update(content: params[:content])
			redirect_to '/'
		else
			render :edit
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		gossip = @comment.gossip
		@comment.destroy
		redirect_to gossip_path(gossip.id)
	end

	private

  	def comment_params
    	params.require(:comment).permit(:content)
  	end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController 
  before_action :user_is_logged_in, except: [:index]

	
	def index
		@gossip = Gossip.all
	end 

	def new
		@gossip = Gossip.new	
	end

	def create
	@gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
    if @gossip.save
      redirect_to "/"
    else
      render "new"
	end 

	end

	def show
		@gossip = Gossip.find(params[:id])
		@user = User.find_by(id: @gossip.user_id)
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		if @gossip.update(gossip_params)
			redirect_to @gossip
		else
			render :edit
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to "/"
	end

private

  	def gossip_params
    	params.permit(:title, :content)
  	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def team
	end

	def contact
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end 

def create
 user = User.find_by(email: params[:email])
 if user && user.authenticate(params[:password])
  session[:user_id] = user.id
  flash[:success] = 'Successfully Logged In!'
  redirect_to '/'
 else
  flash[:warning] = 'Invalid Username or Password'
  redirect_to '/login'
 end
end

 def destroy
  session[:user_id] = nil
  flash[:success] = 'Successfully Logged Out!'
  redirect_to '/login'
 end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def welcome
		 @user = User.find(params[:id])
	end

	def show
		@user = User.all
		@user = User.find(params[:id])
	end 

	def new
	end

	def create
		@user = User.new(
			first_name: params[:first_name],
			last_name: params[:last_name],
			description: params[:description],
			email: params[:email],
			age: params[:age],
			city_id: City.all.sample.id,
			password: params[:password],
			password_confirmation: params[:password_confirmation])
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = 'Successfully create user !'
			redirect_to "/"
		else
			flash[:warning] = 'Invalid email or password'
			redirect_to "/signup"
		end 

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  def current_user
  	User.find_by(id: session[:user_id])
  end



end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/show.html.erb
<br />
<center>
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> City : <%= @city.name %> </li>
    <li class="list-group-item"> Zip_Code : <%= @city.zip_code %> </li>
  </ul>
</div>
<br />

<% @gossip.each do |gossip| %>
<br />
<% if gossip.user.city_id == @city.id %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> Author : <%= gossip.user.first_name %> </h5>
    <p class="card-text">  Title : <%= gossip.title %> </p>
    <a <%= link_to "Voir", gossip_path(gossip.id) %> </a>
  </div>
</div>
<% end %>
<% end %> 

app/views/comment/edit.html.erb
<br />
<p> Pour la modification d'un commentaire, c'est bien ici : </p>
<br /> 
<br />
<html>
  <body>
     <%= form_tag url_for(action: 'update'), method: "put" do %>
    <%= text_area_tag 'content' %>
    <br />
    <%= submit_tag "Update Comment" %>
  <% end %>
  </body>


<br />
<br />
<a class="btn btn-danger" <%= link_to "Delete", comment_path(@comment.id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %> </a> 

</html>

app/views/gossip/edit.html.erb
<p> Pour la modification d'un Gossip, c'est bien ici : </p>
<br /> 


<html>
  <body>
    <!-- ... -->

    <%= form_tag url_for(action: 'update'), method: "put" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Update Post" %>

    <% end %>
    <!-- ... -->
  </body>
</html>

app/views/gossip/index.html.erb
<center>
	<p>Bienvenue ! </p>

<p>Voici la liste des Gossips : </p>

<% @gossip.each_with_index do |gossip| %>
<br />
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> Author : <%= gossip.user.first_name %> </h5>
    <p class="card-text">  Title : <%= gossip.title %> </p>
    <a <%= link_to "Voir", gossip_path(gossip.id) %> </a>
  </div>
</div>

<% end %> 
 </center>         

app/views/gossip/new.html.erb
<p> Pour la création d'un Gossip, c'est bien ici : </p>
<br /> 


<html>
  <body>
    <!-- ... -->

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>
    <!-- ... -->
  </body>
</html>

app/views/gossip/show.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<br />
<center>
<div class="card" style="width: 30rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> Author : <%= @gossip.user.first_name %> </li>
    <li class="list-group-item">Title : <%= @gossip.title%></li>
    <li class="list-group-item">Content : <%= @gossip.content%></li>
    <li class="list-group-item">City : <%= City.find_by(id: @user.city_id).name %> </li>
  </ul>
</div>
<br />

<p> Tu veux en savoir plus sur l'auteur de ce gossip ? <%= link_to "Clique ici", user_path(@user) %>  </p>
<p> Tu veux connaître tous les gossips de cette ville ? <%= link_to "Clique ici", city_path(@user.city_id) %>  </p>

<a class="btn btn-primary" <%= link_to "Update", edit_gossip_path(@gossip.id) %> </a> 
<a class="btn btn-danger" <%= link_to "Delete", gossip_path(@gossip.id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %> </a> 

<br />
<br />
<br />
<br />
<html>
  <body>
     <%= form_tag url_for(action: 'create',
  controller: 'comment'),
  method: "post" do %>
    <%= text_field_tag :gossip_id, @gossip.id, type: 'hidden'%>
    <%= text_area_tag 'content' %>
    <br />
    <%= submit_tag "Send Comment" %>
  <% end %>
  </body>
</html>
<br />
<br />
<br />
<br />

<div class="container">
<div class="row">
<div class="col-sm-12">
<h3>User Comment</h3>
<%= @gossip.comments.each do |comment| %>
</div><!-- /col-sm-12 -->
</div><!-- /row -->
<div class="row">
<div class="col-sm-1">
<div class="thumbnail">
<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
</div><!-- /thumbnail -->
</div><!-- /col-sm-1 -->
<div class="col-sm-5">
<div class="panel panel-default">
<div class="panel-heading">
<strong>  <%= comment.user.first_name %> : </strong> 
</div>
<div class="panel-body">
<%= comment.content %>
<a class="btn btn-primary" <%= link_to "Update", edit_comment_path(comment.id) %> </a> 
</div><!-- /panel-body -->
</div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->
<% end %>
</div><!-- /container -->
</center>

app/views/home/contact.html.erb
<br />
<form id="contact-form" method="post" action="contact" role="form">

    <div class="messages"></div>

    <div class="controls">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_name">Firstname *</label>
                    <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_lastname">Lastname *</label>
                    <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_email">Email *</label>
                    <input id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_need">Please specify your need *</label>
                    <select id="form_need" name="need" class="form-control" required="required" data-error="Please specify your need.">
                        <option value=""></option>
                        <option value="Request quotation">Report a Gossip</option>
                        <option value="Other">Other</option>
                    </select>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="form_message">Message *</label>
                    <textarea id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required="required" data-error="Please, leave us a message."></textarea>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-12">
                <input type="submit" class="btn btn-success btn-send" value="Send message">
            </div>
        </div>
    </div>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/gossip/new">Create Gossip</a>
      <a class="nav-item nav-link" href="/home/team">Team</a>
      <a class="nav-item nav-link" href="/home/contact">Contact</a>
       <% if current_user %>
  Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>
      </li>
    </div>
  </div>
</nav>

  </head>

  <body class="background">
    <%= yield %>
  </body>

  <footer>
    <!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <a href="https://www.facebook.com/emilie.douvier.3"> <i class="fab fa-facebook-f">  </i>  </a>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <a href="https://twitter.com/DouvierEmilie"> <i class="fab fa-twitter"> </i> </a>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <a href="https://www.google.fr/"><i class="fab fa-google-plus-g"> </i> </a>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <a href="https://www.linkedin.com/in/emilie-douvier/"><i class="fab fa-linkedin-in"> </i> </a>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> Emilie-D</a>
    </div>
    <!-- Copyright -->


  </footer>
</html>

app/views/user/new.html.erb
<h2> Create Account</h2>
<%=form_tag "/user", method: :post do %>
 <div>
  <%= label_tag :first_name%>
  <%= text_field_tag :first_name%>
 </div>
 <div>
  <%= label_tag :last_name%>
  <%= text_field_tag :last_name%>
 </div>
 <div>
  <%= label_tag :age%>
  <%= text_field_tag :age%>
 </div>
 <div>
  <%= label_tag :description%>
  <%= text_field_tag :description%>
 </div>
 <div>
  <%= label_tag :email%>
  <%= text_field_tag :email%>
 </div>
 <div>
  <%= label_tag :password%>
  <%= password_field_tag :password%>
 </div>
 <div>
  <%= label_tag :password_confirmation%>
  <%= password_field_tag :password_confirmation%>
 </div>
 
<%= submit_tag 'Sign Up', class: 'btn btn-default'%>
<%end%>

app/views/user/show.html.erb
<br />
<center>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" <%= image_tag 'anonyme.jpg', alt: 'logo' %>
  <div class="card-body">
    <h5 class="card-title">Profil</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> First Name : <%= @user.first_name %> </li>
    <li class="list-group-item"> Last Name : <%= @user.last_name %> </li>
    <li class="list-group-item"> Description : <%= @user.description %> </li>
    <li class="list-group-item"> Email : <%= @user.email%> </li>
    <li class="list-group-item"> Age : <%= @user.age %> </li>
    <li class="list-group-item"> Ville : <%= City.find_by(id: @user.city_id).name %> </li>
  </ul>
</div>
<br />
<p> Tu veux connaître tous les gossips de cette ville ? <%= link_to "Clique ici", city_path(@user.city_id) %>  </p>

</center>

app/views/user/welcome.html.erb
<p> Bonjour bonjour <%= @user.first_name %> </p>